dist: xenial
language: c
script: bash -ex .travis-ci.sh
before_install:
  - sudo add-apt-repository ppa:jonathonf/texlive -y
  - sudo add-apt-repository ppa:apt-fast/stable -y
  - sudo apt-get update -q
  - sudo apt-get install apt-fast -y
  - sudo apt-fast install ocaml ocaml-native-compilers opam texlive-full -y
deploy:
  - provider: pages
    local_dir: manual/htmlman
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: release/*
    skip_cleanup: true
    draft: true
    on:
      tags: true

    