dist: xenial
language: c
script: bash -ex .travis-ci.sh
before_install:
  - sudo add-apt-repository ppa:jonathonf/texlive -y
  - sudo apt-get update -q
  - sudo apt-get install ocaml ocaml-native-compilers opam texlive-full -y